"""
    2.13.5.3 FLEET REST API

    The REST API for the 2.13.5.3 interface of FLEET  # noqa: E501

    The version of the OpenAPI document: 2.13.5.3
    Contact: support@mir-robots.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import mir_fleet_client
from mir_fleet_client.api.software_api import SoftwareApi  # noqa: E501


class TestSoftwareApi(unittest.TestCase):
    """SoftwareApi unit test stubs"""

    def setUp(self):
        self.api = SoftwareApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_software_backups_get(self):
        """Test case for software_backups_get

        GET /software/backups  # noqa: E501
        """
        pass

    def test_software_backups_guid_delete(self):
        """Test case for software_backups_guid_delete

        DELETE /software/backups/{guid}  # noqa: E501
        """
        pass

    def test_software_backups_guid_get(self):
        """Test case for software_backups_guid_get

        GET /software/backups/{guid}  # noqa: E501
        """
        pass

    def test_software_backups_guid_post(self):
        """Test case for software_backups_guid_post

        POST /software/backups/{guid}  # noqa: E501
        """
        pass

    def test_software_backups_post(self):
        """Test case for software_backups_post

        POST /software/backups  # noqa: E501
        """
        pass

    def test_software_logs_get(self):
        """Test case for software_logs_get

        GET /software/logs  # noqa: E501
        """
        pass

    def test_software_logs_guid_get(self):
        """Test case for software_logs_guid_get

        GET /software/logs/{guid}  # noqa: E501
        """
        pass

    def test_software_upgrades_get(self):
        """Test case for software_upgrades_get

        GET /software/upgrades  # noqa: E501
        """
        pass

    def test_software_upgrades_guid_delete(self):
        """Test case for software_upgrades_guid_delete

        DELETE /software/upgrades/{guid}  # noqa: E501
        """
        pass

    def test_software_upgrades_guid_get(self):
        """Test case for software_upgrades_guid_get

        GET /software/upgrades/{guid}  # noqa: E501
        """
        pass

    def test_software_upgrades_guid_post(self):
        """Test case for software_upgrades_guid_post

        POST /software/upgrades/{guid}  # noqa: E501
        """
        pass

    def test_software_upgrades_post(self):
        """Test case for software_upgrades_post

        POST /software/upgrades  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
