"""
    2.13.5.3 FLEET REST API

    The REST API for the 2.13.5.3 interface of FLEET  # noqa: E501

    The version of the OpenAPI document: 2.13.5.3
    Contact: support@mir-robots.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import mir_fleet_client
from mir_fleet_client.api.permissions_api import PermissionsApi  # noqa: E501


class TestPermissionsApi(unittest.TestCase):
    """PermissionsApi unit test stubs"""

    def setUp(self):
        self.api = PermissionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_permissions_get(self):
        """Test case for permissions_get

        GET /permissions  # noqa: E501
        """
        pass

    def test_permissions_guid_delete(self):
        """Test case for permissions_guid_delete

        DELETE /permissions/{guid}  # noqa: E501
        """
        pass

    def test_permissions_guid_get(self):
        """Test case for permissions_guid_get

        GET /permissions/{guid}  # noqa: E501
        """
        pass

    def test_permissions_post(self):
        """Test case for permissions_post

        POST /permissions  # noqa: E501
        """
        pass

    def test_user_groups_user_group_guid_permissions_get(self):
        """Test case for user_groups_user_group_guid_permissions_get

        GET /user_groups/{user_group_guid}/permissions  # noqa: E501
        """
        pass

    def test_user_groups_user_group_guid_permissions_post(self):
        """Test case for user_groups_user_group_guid_permissions_post

        POST /user_groups/{user_group_guid}/permissions  # noqa: E501
        """
        pass

    def test_users_me_permissions_get(self):
        """Test case for users_me_permissions_get

        GET /users/me/permissions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
