"""
    2.13.5.3 FLEET REST API

    The REST API for the 2.13.5.3 interface of FLEET  # noqa: E501

    The version of the OpenAPI document: 2.13.5.3
    Contact: support@mir-robots.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import mir_fleet_client
from mir_fleet_client.api.opcua_scanner_api import OpcuaScannerApi  # noqa: E501


class TestOpcuaScannerApi(unittest.TestCase):
    """OpcuaScannerApi unit test stubs"""

    def setUp(self):
        self.api = OpcuaScannerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_elevators_guid_opcua_scanner_get(self):
        """Test case for elevators_guid_opcua_scanner_get

        GET /elevators/{guid}/opcua_scanner  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
