"""
    2.13.5.3 FLEET REST API

    The REST API for the 2.13.5.3 interface of FLEET  # noqa: E501

    The version of the OpenAPI document: 2.13.5.3
    Contact: support@mir-robots.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import mir_fleet_client
from mir_fleet_client.api.reset_api import ResetApi  # noqa: E501


class TestResetApi(unittest.TestCase):
    """ResetApi unit test stubs"""

    def setUp(self):
        self.api = ResetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_reset_post(self):
        """Test case for reset_post

        POST /reset  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
