"""
    2.13.5.3 FLEET REST API

    The REST API for the 2.13.5.3 interface of FLEET  # noqa: E501

    The version of the OpenAPI document: 2.13.5.3
    Contact: support@mir-robots.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import mir_fleet_client
from mir_fleet_client.api.service_book_api import ServiceBookApi  # noqa: E501


class TestServiceBookApi(unittest.TestCase):
    """ServiceBookApi unit test stubs"""

    def setUp(self):
        self.api = ServiceBookApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_service_book_get(self):
        """Test case for service_book_get

        GET /service_book  # noqa: E501
        """
        pass

    def test_service_book_guid_delete(self):
        """Test case for service_book_guid_delete

        DELETE /service_book/{guid}  # noqa: E501
        """
        pass

    def test_service_book_guid_get(self):
        """Test case for service_book_guid_get

        GET /service_book/{guid}  # noqa: E501
        """
        pass

    def test_service_book_post(self):
        """Test case for service_book_post

        POST /service_book  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
