"""
    2.13.5.3 FLEET REST API

    The REST API for the 2.13.5.3 interface of FLEET  # noqa: E501

    The version of the OpenAPI document: 2.13.5.3
    Contact: support@mir-robots.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import mir_fleet_client
from mir_fleet_client.api.missions_api import MissionsApi  # noqa: E501


class TestMissionsApi(unittest.TestCase):
    """MissionsApi unit test stubs"""

    def setUp(self):
        self.api = MissionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_mission_groups_group_id_missions_get(self):
        """Test case for mission_groups_group_id_missions_get

        GET /mission_groups/{group_id}/missions  # noqa: E501
        """
        pass

    def test_missions_get(self):
        """Test case for missions_get

        GET /missions  # noqa: E501
        """
        pass

    def test_missions_guid_definition_get(self):
        """Test case for missions_guid_definition_get

        GET /missions/{guid}/definition  # noqa: E501
        """
        pass

    def test_missions_guid_delete(self):
        """Test case for missions_guid_delete

        DELETE /missions/{guid}  # noqa: E501
        """
        pass

    def test_missions_guid_get(self):
        """Test case for missions_guid_get

        GET /missions/{guid}  # noqa: E501
        """
        pass

    def test_missions_guid_put(self):
        """Test case for missions_guid_put

        PUT /missions/{guid}  # noqa: E501
        """
        pass

    def test_missions_guid_qualified_robots_get(self):
        """Test case for missions_guid_qualified_robots_get

        GET /missions/{guid}/qualified_robots  # noqa: E501
        """
        pass

    def test_missions_mission_id_actions_get(self):
        """Test case for missions_mission_id_actions_get

        GET /missions/{mission_id}/actions  # noqa: E501
        """
        pass

    def test_missions_mission_id_actions_guid_delete(self):
        """Test case for missions_mission_id_actions_guid_delete

        DELETE /missions/{mission_id}/actions/{guid}  # noqa: E501
        """
        pass

    def test_missions_mission_id_actions_guid_get(self):
        """Test case for missions_mission_id_actions_guid_get

        GET /missions/{mission_id}/actions/{guid}  # noqa: E501
        """
        pass

    def test_missions_mission_id_actions_guid_put(self):
        """Test case for missions_mission_id_actions_guid_put

        PUT /missions/{mission_id}/actions/{guid}  # noqa: E501
        """
        pass

    def test_missions_mission_id_actions_post(self):
        """Test case for missions_mission_id_actions_post

        POST /missions/{mission_id}/actions  # noqa: E501
        """
        pass

    def test_missions_post(self):
        """Test case for missions_post

        POST /missions  # noqa: E501
        """
        pass

    def test_sessions_session_id_missions_get(self):
        """Test case for sessions_session_id_missions_get

        GET /sessions/{session_id}/missions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
