"""
    2.13.5.3 FLEET REST API

    The REST API for the 2.13.5.3 interface of FLEET  # noqa: E501

    The version of the OpenAPI document: 2.13.5.3
    Contact: support@mir-robots.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import mir_fleet_client
from mir_fleet_client.api.me_api import MeApi  # noqa: E501


class TestMeApi(unittest.TestCase):
    """MeApi unit test stubs"""

    def setUp(self):
        self.api = MeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_users_me_get(self):
        """Test case for users_me_get

        GET /users/me  # noqa: E501
        """
        pass

    def test_users_me_permissions_get(self):
        """Test case for users_me_permissions_get

        GET /users/me/permissions  # noqa: E501
        """
        pass

    def test_users_me_put(self):
        """Test case for users_me_put

        PUT /users/me  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
