"""
    2.13.5.3 FLEET REST API

    The REST API for the 2.13.5.3 interface of FLEET  # noqa: E501

    The version of the OpenAPI document: 2.13.5.3
    Contact: support@mir-robots.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import mir_fleet_client
from mir_fleet_client.model.put_setting import PutSetting


class TestPutSetting(unittest.TestCase):
    """PutSetting unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPutSetting(self):
        """Test PutSetting"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PutSetting()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
