"""
    2.13.5.3 FLEET REST API

    The REST API for the 2.13.5.3 interface of FLEET  # noqa: E501

    The version of the OpenAPI document: 2.13.5.3
    Contact: support@mir-robots.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import mir_fleet_client
from mir_fleet_client.model.get_session_import import GetSessionImport


class TestGetSessionImport(unittest.TestCase):
    """GetSessionImport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetSessionImport(self):
        """Test GetSessionImport"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetSessionImport()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
