"""
    2.13.5.3 FLEET REST API

    The REST API for the 2.13.5.3 interface of FLEET  # noqa: E501

    The version of the OpenAPI document: 2.13.5.3
    Contact: support@mir-robots.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import mir_fleet_client
from mir_fleet_client.api.elevator_floors_api import ElevatorFloorsApi  # noqa: E501


class TestElevatorFloorsApi(unittest.TestCase):
    """ElevatorFloorsApi unit test stubs"""

    def setUp(self):
        self.api = ElevatorFloorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_elevator_floors_get(self):
        """Test case for elevator_floors_get

        GET /elevator_floors  # noqa: E501
        """
        pass

    def test_elevator_floors_guid_delete(self):
        """Test case for elevator_floors_guid_delete

        DELETE /elevator_floors/{guid}  # noqa: E501
        """
        pass

    def test_elevator_floors_guid_get(self):
        """Test case for elevator_floors_guid_get

        GET /elevator_floors/{guid}  # noqa: E501
        """
        pass

    def test_elevator_floors_guid_put(self):
        """Test case for elevator_floors_guid_put

        PUT /elevator_floors/{guid}  # noqa: E501
        """
        pass

    def test_elevator_floors_post(self):
        """Test case for elevator_floors_post

        POST /elevator_floors  # noqa: E501
        """
        pass

    def test_sessions_session_id_elevator_floors_get(self):
        """Test case for sessions_session_id_elevator_floors_get

        GET /sessions/{session_id}/elevator_floors  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
