"""
    2.13.5.3 FLEET REST API

    The REST API for the 2.13.5.3 interface of FLEET  # noqa: E501

    The version of the OpenAPI document: 2.13.5.3
    Contact: support@mir-robots.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import mir_fleet_client
from mir_fleet_client.api.definition_api import DefinitionApi  # noqa: E501


class TestDefinitionApi(unittest.TestCase):
    """DefinitionApi unit test stubs"""

    def setUp(self):
        self.api = DefinitionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_missions_guid_definition_get(self):
        """Test case for missions_guid_definition_get

        GET /missions/{guid}/definition  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
