"""
    2.13.5.3 FLEET REST API

    The REST API for the 2.13.5.3 interface of FLEET  # noqa: E501

    The version of the OpenAPI document: 2.13.5.3
    Contact: support@mir-robots.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import mir_fleet_client
from mir_fleet_client.api.path_guides_positions_api import PathGuidesPositionsApi  # noqa: E501


class TestPathGuidesPositionsApi(unittest.TestCase):
    """PathGuidesPositionsApi unit test stubs"""

    def setUp(self):
        self.api = PathGuidesPositionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_path_guides_positions_get(self):
        """Test case for path_guides_positions_get

        GET /path_guides_positions  # noqa: E501
        """
        pass

    def test_path_guides_positions_guid_delete(self):
        """Test case for path_guides_positions_guid_delete

        DELETE /path_guides_positions/{guid}  # noqa: E501
        """
        pass

    def test_path_guides_positions_guid_get(self):
        """Test case for path_guides_positions_guid_get

        GET /path_guides_positions/{guid}  # noqa: E501
        """
        pass

    def test_path_guides_positions_guid_put(self):
        """Test case for path_guides_positions_guid_put

        PUT /path_guides_positions/{guid}  # noqa: E501
        """
        pass

    def test_path_guides_positions_post(self):
        """Test case for path_guides_positions_post

        POST /path_guides_positions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
