"""
    2.13.5.3 FLEET REST API

    The REST API for the 2.13.5.3 interface of FLEET  # noqa: E501

    The version of the OpenAPI document: 2.13.5.3
    Contact: support@mir-robots.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import mir_fleet_client
from mir_fleet_client.api.upgrades_api import UpgradesApi  # noqa: E501


class TestUpgradesApi(unittest.TestCase):
    """UpgradesApi unit test stubs"""

    def setUp(self):
        self.api = UpgradesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_software_upgrades_get(self):
        """Test case for software_upgrades_get

        GET /software/upgrades  # noqa: E501
        """
        pass

    def test_software_upgrades_guid_delete(self):
        """Test case for software_upgrades_guid_delete

        DELETE /software/upgrades/{guid}  # noqa: E501
        """
        pass

    def test_software_upgrades_guid_get(self):
        """Test case for software_upgrades_guid_get

        GET /software/upgrades/{guid}  # noqa: E501
        """
        pass

    def test_software_upgrades_guid_post(self):
        """Test case for software_upgrades_guid_post

        POST /software/upgrades/{guid}  # noqa: E501
        """
        pass

    def test_software_upgrades_post(self):
        """Test case for software_upgrades_post

        POST /software/upgrades  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
