"""
    2.13.5.3 FLEET REST API

    The REST API for the 2.13.5.3 interface of FLEET  # noqa: E501

    The version of the OpenAPI document: 2.13.5.3
    Contact: support@mir-robots.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import mir_fleet_client
from mir_fleet_client.api.backups_api import BackupsApi  # noqa: E501


class TestBackupsApi(unittest.TestCase):
    """BackupsApi unit test stubs"""

    def setUp(self):
        self.api = BackupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_software_backups_get(self):
        """Test case for software_backups_get

        GET /software/backups  # noqa: E501
        """
        pass

    def test_software_backups_guid_delete(self):
        """Test case for software_backups_guid_delete

        DELETE /software/backups/{guid}  # noqa: E501
        """
        pass

    def test_software_backups_guid_get(self):
        """Test case for software_backups_guid_get

        GET /software/backups/{guid}  # noqa: E501
        """
        pass

    def test_software_backups_guid_post(self):
        """Test case for software_backups_guid_post

        POST /software/backups/{guid}  # noqa: E501
        """
        pass

    def test_software_backups_post(self):
        """Test case for software_backups_post

        POST /software/backups  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
