"""
    2.13.5.3 FLEET REST API

    The REST API for the 2.13.5.3 interface of FLEET  # noqa: E501

    The version of the OpenAPI document: 2.13.5.3
    Contact: support@mir-robots.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import mir_fleet_client
from mir_fleet_client.api.chargers_api import ChargersApi  # noqa: E501


class TestChargersApi(unittest.TestCase):
    """ChargersApi unit test stubs"""

    def setUp(self):
        self.api = ChargersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_chargers_charger_id_charging_groups_get(self):
        """Test case for chargers_charger_id_charging_groups_get

        GET /chargers/{charger_id}/charging_groups  # noqa: E501
        """
        pass

    def test_charging_groups_group_id_chargers_charger_id_delete(self):
        """Test case for charging_groups_group_id_chargers_charger_id_delete

        DELETE /charging_groups/{group_id}/chargers/{charger_id}  # noqa: E501
        """
        pass

    def test_charging_groups_group_id_chargers_charger_id_get(self):
        """Test case for charging_groups_group_id_chargers_charger_id_get

        GET /charging_groups/{group_id}/chargers/{charger_id}  # noqa: E501
        """
        pass

    def test_charging_groups_group_id_chargers_get(self):
        """Test case for charging_groups_group_id_chargers_get

        GET /charging_groups/{group_id}/chargers  # noqa: E501
        """
        pass

    def test_charging_groups_group_id_chargers_post(self):
        """Test case for charging_groups_group_id_chargers_post

        POST /charging_groups/{group_id}/chargers  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
