"""
    2.13.5.3 FLEET REST API

    The REST API for the 2.13.5.3 interface of FLEET  # noqa: E501

    The version of the OpenAPI document: 2.13.5.3
    Contact: support@mir-robots.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import mir_fleet_client
from mir_fleet_client.api.users_api import UsersApi  # noqa: E501


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_users_auth_delete(self):
        """Test case for users_auth_delete

        DELETE /users/auth  # noqa: E501
        """
        pass

    def test_users_auth_post(self):
        """Test case for users_auth_post

        POST /users/auth  # noqa: E501
        """
        pass

    def test_users_get(self):
        """Test case for users_get

        GET /users  # noqa: E501
        """
        pass

    def test_users_guid_delete(self):
        """Test case for users_guid_delete

        DELETE /users/{guid}  # noqa: E501
        """
        pass

    def test_users_guid_get(self):
        """Test case for users_guid_get

        GET /users/{guid}  # noqa: E501
        """
        pass

    def test_users_guid_put(self):
        """Test case for users_guid_put

        PUT /users/{guid}  # noqa: E501
        """
        pass

    def test_users_me_get(self):
        """Test case for users_me_get

        GET /users/me  # noqa: E501
        """
        pass

    def test_users_me_permissions_get(self):
        """Test case for users_me_permissions_get

        GET /users/me/permissions  # noqa: E501
        """
        pass

    def test_users_me_put(self):
        """Test case for users_me_put

        PUT /users/me  # noqa: E501
        """
        pass

    def test_users_post(self):
        """Test case for users_post

        POST /users  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
