"""
    2.13.5.3 FLEET REST API

    The REST API for the 2.13.5.3 interface of FLEET  # noqa: E501

    The version of the OpenAPI document: 2.13.5.3
    Contact: support@mir-robots.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import mir_fleet_client
from mir_fleet_client.api.settings_api import SettingsApi  # noqa: E501


class TestSettingsApi(unittest.TestCase):
    """SettingsApi unit test stubs"""

    def setUp(self):
        self.api = SettingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_setting_groups_settings_group_id_settings_advanced_get(self):
        """Test case for setting_groups_settings_group_id_settings_advanced_get

        GET /setting_groups/{settings_group_id}/settings/advanced  # noqa: E501
        """
        pass

    def test_setting_groups_settings_group_id_settings_get(self):
        """Test case for setting_groups_settings_group_id_settings_get

        GET /setting_groups/{settings_group_id}/settings  # noqa: E501
        """
        pass

    def test_settings_advanced_get(self):
        """Test case for settings_advanced_get

        GET /settings/advanced  # noqa: E501
        """
        pass

    def test_settings_advanced_id_get(self):
        """Test case for settings_advanced_id_get

        GET /settings/advanced/{id}  # noqa: E501
        """
        pass

    def test_settings_advanced_id_put(self):
        """Test case for settings_advanced_id_put

        PUT /settings/advanced/{id}  # noqa: E501
        """
        pass

    def test_settings_get(self):
        """Test case for settings_get

        GET /settings  # noqa: E501
        """
        pass

    def test_settings_id_get(self):
        """Test case for settings_id_get

        GET /settings/{id}  # noqa: E501
        """
        pass

    def test_settings_id_put(self):
        """Test case for settings_id_put

        PUT /settings/{id}  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
