"""
    2.13.5.3 FLEET REST API

    The REST API for the 2.13.5.3 interface of FLEET  # noqa: E501

    The version of the OpenAPI document: 2.13.5.3
    Contact: support@mir-robots.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import mir_fleet_client
from mir_fleet_client.api.elevator_status_api import ElevatorStatusApi  # noqa: E501


class TestElevatorStatusApi(unittest.TestCase):
    """ElevatorStatusApi unit test stubs"""

    def setUp(self):
        self.api = ElevatorStatusApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_elevator_status_get(self):
        """Test case for elevator_status_get

        GET /elevator_status  # noqa: E501
        """
        pass

    def test_elevator_status_guid_get(self):
        """Test case for elevator_status_guid_get

        GET /elevator_status/{guid}  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
