"""
    2.13.5.3 FLEET REST API

    The REST API for the 2.13.5.3 interface of FLEET  # noqa: E501

    The version of the OpenAPI document: 2.13.5.3
    Contact: support@mir-robots.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import mir_fleet_client
from mir_fleet_client.api.ssl_api import SslApi  # noqa: E501


class TestSslApi(unittest.TestCase):
    """SslApi unit test stubs"""

    def setUp(self):
        self.api = SslApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ssl_cert_delete(self):
        """Test case for ssl_cert_delete

        DELETE /ssl/cert  # noqa: E501
        """
        pass

    def test_ssl_cert_post(self):
        """Test case for ssl_cert_post

        POST /ssl/cert  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
