"""
    2.13.5.3 FLEET REST API

    The REST API for the 2.13.5.3 interface of FLEET  # noqa: E501

    The version of the OpenAPI document: 2.13.5.3
    Contact: support@mir-robots.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import mir_fleet_client
from mir_fleet_client.api.sw_version_status_api import SwVersionStatusApi  # noqa: E501


class TestSwVersionStatusApi(unittest.TestCase):
    """SwVersionStatusApi unit test stubs"""

    def setUp(self):
        self.api = SwVersionStatusApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sw_version_status_get(self):
        """Test case for sw_version_status_get

        GET /sw_version_status  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
