"""
    2.13.5.3 FLEET REST API

    The REST API for the 2.13.5.3 interface of FLEET  # noqa: E501

    The version of the OpenAPI document: 2.13.5.3
    Contact: support@mir-robots.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import mir_fleet_client
from mir_fleet_client.model.post_carts import PostCarts


class TestPostCarts(unittest.TestCase):
    """PostCarts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostCarts(self):
        """Test PostCarts"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostCarts()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
