"""
    2.13.5.3 FLEET REST API

    The REST API for the 2.13.5.3 interface of FLEET  # noqa: E501

    The version of the OpenAPI document: 2.13.5.3
    Contact: support@mir-robots.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import mir_fleet_client
from mir_fleet_client.api.logs_api import LogsApi  # noqa: E501


class TestLogsApi(unittest.TestCase):
    """LogsApi unit test stubs"""

    def setUp(self):
        self.api = LogsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_software_logs_get(self):
        """Test case for software_logs_get

        GET /software/logs  # noqa: E501
        """
        pass

    def test_software_logs_guid_get(self):
        """Test case for software_logs_guid_get

        GET /software/logs/{guid}  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
