"""
    2.13.5.3 FLEET REST API

    The REST API for the 2.13.5.3 interface of FLEET  # noqa: E501

    The version of the OpenAPI document: 2.13.5.3
    Contact: support@mir-robots.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import mir_fleet_client
from mir_fleet_client.api.shelfs_api import ShelfsApi  # noqa: E501


class TestShelfsApi(unittest.TestCase):
    """ShelfsApi unit test stubs"""

    def setUp(self):
        self.api = ShelfsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_docking_offsets_shelfs_get(self):
        """Test case for docking_offsets_shelfs_get

        GET /docking_offsets/shelfs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
